name: Maven Build
description: Run a Maven Build

inputs:
  build-command:
    description: The Maven command to build the project. The default is `package`.
    required: false
    default: install
  release-name:
    description: The Maven artifact name and version.
    required: true
  build-flags: 
    description: The Maven build flags
    required: false
    default: '-Dmaven.repo.local=$GITHUB_WORKSPACE/.m2'
  build-profiles:
    description: The Maven build profiles
    required: false
    default: 'daml,scala,typescript,golang,csharp8,csharp9,kotlin,python,full,gpg,excel'
  maven-settings:
    description: The Maven settings file
    required: false
    default: $GITHUB_WORKSPACE/settings.xml

runs:
  using: "composite"
  steps:
    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64
        cache: maven
        server-id: ossrh
        server-username: ${{ secrets.CI_DEPLOY_USERNAME }}
        server-password: ${{ secrets.CI_DEPLOY_PASSWORD }}
        settings-path: ${{ inputs.maven-settings }}
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
    - name: Set artifact version with Maven
      shell: bash
      run: mvn ${{ inputs.build-flags }} versions:set -DnewVersion=${{ inputs.release-name }} versions:update-child-modules -DallowSnapshots=true 
    - name: Build and deploy artifact with Maven
      shell: bash
      run: mvn ${{ inputs.build-flags }} clean ${{ inputs.build-command }} -P ${{ inputs.build-profiles }}
